# Generated by Django 5.2.1 on 2025-05-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_product_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
